### ISSUE TITLE
Class Spatie\OpenTelemetry\Drivers\Multidriver not comply with psr-4 autoloading standard.

### ISSUE THREAD

**Issue by a-h-abid** [spatie/laravel-open-telemetry#12]
When installing `spatie/laravel-open-telemetry` using composer require on fresh laravel 9, getting the below error:

```
Class Spatie\OpenTelemetry\Drivers\Multidriver located in ./vendor/spatie/laravel-open-telemetry/src/Drivers/MultiDriver.php does not comply with psr-4 autoloading standard. Skipping.
```

Laravel version 9.48.0
This package version: 0.0.3
Composer version: 2.5.1

**Comment by freekmurze** [comment]
This package is still in development, so errors like this might still occur. Feel free to send a PR if you need this fixed soon.
