### ISSUE TITLE
ErrorException   /artisan Undefined array key "basic_auth"

### ISSUE THREAD

**Issue by SardorAlif** [spatie/laravel-open-telemetry#34]
<img width="853" alt="Снимок экрана 2024-01-12 в 10 04 51" src="https://github.com/spatie/laravel-open-telemetry/assets/152947432/96bda473-ccb4-488e-a4d0-34f480e92060">
<img width="1196" alt="Снимок экрана 2024-01-12 в 10 05 16" src="https://github.com/spatie/laravel-open-telemetry/assets/152947432/9b8be3ff-0697-48b2-ac53-2fec0906a7e5">

The error you're encountering in the HttpDriver.php file of the spatie/laravel-open-telemetry package is related to the use of an undefined array key basic_auth. This happens in PHP when you try to access an array element that doesn't exist. In your code, the error occurs because the code attempts to access $this->options['basic_auth'] without first ensuring that this key exists in the $options array.

The issue arises in this segment of the code:

`->when($this->options['basic_auth'], function (Factory $client) {
    $client->withBasicAuth(
        $this->options['basic_auth']['username'],
        $this->options['basic_auth']['password'],
    );
})
`
Here, $this->options['basic_auth'] is used as a condition in the when method, assuming that it is always set. However, if it's not set in the $options array, it will lead to an "Undefined array key" error.

To fix this issue, you should ensure that basic_auth is set before using it. You can use the PHP isset() function for this purpose. Modify your code as follows:

php
`->when(isset($this->options['basic_auth']), function (Factory $client) {
    $client->withBasicAuth(
        $this->options['basic_auth']['username'],
        $this->options['basic_auth']['password'],
    );
})
`

This change will check if basic_auth is set in the $options array before attempting to use it, thus preventing the error.

**Comment by freekmurze** [comment]
Fixed in the latest release
